---
title: "妊娠患者をERで診たとき"
subtitle: "婦人科がとってくれない・・・・・・"
date: "2026-11-27"
format:
  clean-revealjs:
    toc: true
    toc-depth: 1
    slide-level: 2
    theme: default
    scrollable: true
    smaller: true
    transition: slide
    incremental: false
    pdf-separate-fragments: false
    pdf-max-pages-per-slide: 3
    slide-number: true
    footer: '<a href="../../medicine/index.html">Medicine</a> · <a href="../../statistics/index.html">Statistics</a> · <a href="../../index.html">Home</a>'
author:
  - name: Nozomi Niimi
    orcid: 0000-0002-6909-0740
    email: figarofuga@gmail.com
    affiliations: 東京医療センター総合内科
date-format: "YYYY-MM-DD"
engine: knitr
execute: 
  error: false
  warning: false
  echo: false
  cache: false
knitr: 
  opts_chunk: 
    dev: svglite
    fig-format: svg
bibliography: references.bib
---

```{css}
<style>
/* スライド幅の 1/2 */
.half-table {
  width: 50%;
}

.half-table table {
  width: 100%;
}

/* スライド幅の 1/4 */
.quad-table {
  width: 25%;
}

.quad-table table {
  width: 100%;
}

/* 中央寄せしたい場合 */
.center-table {
  margin-left: auto;
  margin-right: auto;
}

/* 左寄せしたい場合 */
.left-table {
  margin-left: 0;
  margin-right: auto;
}

/* 表を少しコンパクトに */
.compact-table table {
  font-size: 0.75em;
}

.compact-table th,
.compact-table td {
  padding: 0.25em 0.45em;
  line-height: 1.1;
}
</style>
```

# ER診療について

## 妊婦の特徴

- 若年女性が多い
  - いわゆる高齢者がかかる疾患にはかからない
- 妊娠により、種々の変化が起こる
  - 身体所見(特に腹痛で)が大きく変わる
  - Vital signや採血結果の正常値が変わる
- 一方で、造影剤や放射線などの検査の限界が多い
- さらに使える薬剤も限定される → (少なくとも自分は)苦手意識がある

# 正常妊娠概論

## 妊娠の時期による影響

| 系統 | 項目 | 変化 |
|----|----|----|
| **循環** | 末梢血管抵抗 | ↓ |
|  | 血圧 | 16〜24週 ↓，その後 →〜↗ |
|  | 循環血液量 | ↑ 40〜50% |
| **腎機能** | 血清クレアチニン | ↓（正常平均 0.5 mg/dL, 上限 0.7 mg/dL） |
| 血液関連 | Hct/Hgb | ↓（35%未満）/ ↓（～10.5 g/dL） |
|  | 白血球数 | ↑（〜15,000，特に分娩時 ↑） |
|  | 血小板数 | ↓ |
|  | 凝固能 | ↑ |
| **呼吸機能** |  | 生理的過換気 |
| **糖代謝** | 生理的インスリン抵抗性 | ↑ |
| **甲状腺機能** | 妊娠初期：hCGの影響 | ↗ |
|  | 妊娠中期〜後期 | ↘ |
| **腸管機能** |  | ↓ |

妊娠による影響

## 妊娠による変化 ～ Vital sign

## 妊娠による変化 ～ 身体所見

## 妊娠による変化 ～ 採血結果

# 妊婦への検査

- 15-20%は流産あるいは早産など？

## 放射線検査による被曝量

| 検査方法     | 部位   | 平均被ばく線量（mGy） | 最大被ばく線量（mGy） |
|--------------|--------|----------------------:|----------------------:|
| **単純撮影** | 頭部   |              0.01以下 |              0.01以下 |
|              | 胸部   |              0.01以下 |              0.01以下 |
|              | 腹部   |                   1.4 |                   4.2 |
|              | 腰椎   |                   1.7 |                    10 |
|              | 骨盤部 |                   1.1 |                     4 |
| **CT検査**   | 頭部   |             0.005以下 |             0.005以下 |
|              | 胸部   |                  0.06 |                  0.96 |
|              | 腹部   |                     8 |                    49 |
|              | 腰椎   |                   2.4 |                   8.6 |
|              | 骨盤部 |                    25 |                    79 |

## 妊娠の時期による影響～放射線

## 妊婦への検査～Ｘ線

## 妊婦への検査～CT検査

どうやってもダメ？

## 妊婦への検査～MRI検査

# 妊婦への治療

## 妊娠の時期による影響～薬剤の影響

妊娠初期

| 一般名または医薬品群名 | 代表的商品名 | 報告された催奇形性・胎児毒性 |
|------------------------|------------------------|------------------------|
| カルバマゼピン | テグレトール，他 | 催奇形性 |
| シクロホスファミド | エンドキサン | 催奇形性 |
| ダナゾール | ボンゾール，他 | 催奇形性：女児外性器の男性化 |
| チアマゾール | メルカゾール | 催奇形性：MMI奇形症候群 |
| バルプロ酸ナトリウム | デパケン、セレニカR，他 | 催奇形性：二分脊椎、胎児バルプロ酸症候群 |
| ビタミンA（大量） | チョコラA，他 | 催奇形性 |
| フェニトイン | アレビアチン、ヒダントール，他 | 催奇形性：胎児ヒダントイン症候群 |
| フェノバルビタール | フェノバール，他 | 催奇形性：口唇・口蓋裂，他 |
| ミコフェノール酸モフェチル | セルセプト | 催奇形性：外耳・顔面奇形、口唇・口蓋裂、遠位四肢・心臓・食道・腎臓の奇形，他／流産 |
| ミソプロストール | サイトテック | メビウス症候群、四肢切断、子宮収縮、流産 |
| メトトレキサート | リウマトレックス，他 | 催奇形性：メトトレキサート胎芽病 |
| ワルファリンカリウム（クマリン系抗凝血薬） | ワーファリン，他 | 催奇形性：ワルファリン胎芽病、点状軟骨異栄養症、中枢神経異常 |

妊娠中・後期

| 一般名または医薬品群名 | 代表的商品名 | 報告された催奇形性・胎児毒性 |
|------------------------|------------------------|------------------------|
| アミノグリコシド系抗結核薬 | カナマイシン注、ストレプトマイシン注 | 胎児毒性：非可逆的第VIII脳神経障害、先天性聴力障害 |
| アンジオテンシン変換酵素阻害薬（ACE-I） | カプトプリル、レニベース，他 | 胎児毒性：胎児腎障害・無尿・羊水過少、肺低形成、Potter sequence |
| アンジオテンシンII受容体拮抗薬（ARB） | ニューロタン、バルサルタン，他 | 胎児毒性：胎児腎障害・無尿・羊水過少、肺低形成、Potter sequence |
| テトラサイクリン系抗菌薬 | アクロマイシン、レダマイシン、ミノマイシン，他 | 胎児毒性：歯牙の着色、エナメル質形成不全 |
| ミソプロストール | サイトテック | 子宮収縮、流早産 |

妊娠後期

| 一般名または医薬品群名 | 代表的商品名 | 報告された催奇形性・胎児毒性 |
|------------------------|------------------------|------------------------|
| アミノグリコシド系抗結核薬 | カナマイシン注、ストレプトマイシン注 | 胎児毒性：非可逆的第VIII脳神経障害、先天性聴力障害 |
| アンジオテンシン変換酵素阻害薬（ACE-I） | カプトプリル、レニベース，他 | 胎児毒性：胎児腎障害・無尿・羊水過少、肺低形成、Potter sequence |
| アンジオテンシンII受容体拮抗薬（ARB） | ニューロタン、バルサルタン，他 | 胎児毒性：胎児腎障害・無尿・羊水過少、肺低形成、Potter sequence |
| テトラサイクリン系抗菌薬 | アクロマイシン、レダマイシン、ミノマイシン，他 | 胎児毒性：歯牙の着色、エナメル質形成不全 |
| ミソプロストール | サイトテック | 子宮収縮、流早産 |
| 非ステロイド系抗炎症薬（NSAIDs）（インドメタシン、ジクロフェナクナトリウム，他） | インダシン、ボルタレン，他 | 胎児毒性：動脈管収縮、胎児循環遷延、羊水過少、新生児壊死性腸炎 |

Timingでダメな薬

## どの薬が使える？

| 分類 | 薬剤系統 | 妊娠中の使用に関して |
|------------------------|------------------------|------------------------|
| **主な抗菌薬** | ペニシリン系/セフェム系 | 個々の薬剤についての情報は限られているが、妊娠初期の使用により先天異常発生リスクは上昇しないと考えられる。 |
|  | アミノグリコシド系 | ゲンタマイシンやストレプトマイシンでは妊娠初期の使用により先天異常発生リスクは大きく上昇しないと報告されている。妊娠期の使用により、聴覚障害の影響が報告されている。 |
|  | マクロライド系 | アジスロマイシン、エリスロマイシン、クラリスロマイシンでは妊娠初期の使用により先天異常の発生リスクは大きく上昇しないと報告されている。エリスロマイシンの新生児への直接投与により幽門狭窄の報告があるが、妊娠中の使用による影響についてはいくつかの報告で否定されている。 |
|  | テトラサイクリン系 | テトラサイクリンでは、妊娠初期の使用により先天異常発生リスクは大きく上昇しないと報告されている。歯牙の石灰化が始まる時期（妊娠4〜5カ月以降）の使用では歯牙の着色が起こる可能性がある。 |
|  | ニューキノロン系 | キノロン系薬剤の妊娠初期の使用により先天異常発生リスクは大きく上昇しないと報告されている。 |
| **主な解熱鎮痛薬** | アセトアミノフェン | 妊娠初期の使用により先天異常発生リスクは大きく上昇しないと報告されている。 |
|  | NSAIDs | 妊娠初期の使用により先天異常発生リスクは大きく上昇しないと報告されている。妊娠後期の使用により胎児の動脈管の早期閉鎖が起こり、出生後に遷延性肺高血圧症や動脈管開存症が起こる可能性がある。 |

抗菌薬と解熱剤

# 特に知っておくべき妊婦の疾患

## 無症候性膿尿/細菌尿

## 腹痛の部位

# Case study

## 急性腹症の患者

## 気管支喘息の患者

## 発熱で検査をしたら膿尿があった患者

## Thank you for your listening!!

## Reference

::: {#refs}
:::