---
title: "脳梗塞予防の抗血栓薬のエトセトラ"
lang: ja
format:
  clean-revealjs:
  # revealjs:
    toc: true
    toc-depth: 1
    slide-level: 2
    theme: default
    scrollable: true
    smaller: true
    transition: slide
    incremental: false
    pdf-separate-fragments: false
    pdf-max-pages-per-slide: 3
    slide-number: true
    footer: '<a href="../../medicine/index.html">Medicine</a> · <a href="../../statistics/index.html">Statistics</a> · <a href="../../index.html">Home</a>'
author:
  - name: Nozomi Niimi
    orcid: 0000-0002-6909-0740
    email: figarofuga@gmail.com
    affiliations: 東京医療センター総合内科
date-format: "YYYY-MM-DD"
engine: knitr
execute: 
  error: false
  warning: false
  echo: false
  cache: false
knitr: 
  opts_chunk: 
    dev: svglite
    fig-format: svg
date: "2026-09-01"
bibliography: references.bib
---

## 本スライドの目的

- (脳梗塞治療に関して)抗血血栓薬の実臨床の迷いどころを悩む
- 基本的にEvidenceがしっかりとある、"明らかな正解"は書きません
- 明らかな答えがないことに関して、「なぜ？その選択をする？」という事について考えることを目的とします

## 症例 1

- 64歳男性、DM, HTN, Dlp背景
- 3日前発症のアテローム性脳梗塞を発症
- NIHSSは10点
- 初期治療は？

## いつDAPTをするの？

- 基本は「発症早期」の「非心原性」のHigh risk TIAまたは軽症脳梗塞
  - TIAとしてはABCD2 4点以上で脳梗塞としてはNIHSS 5点以下
- 本来なら、3日以上前でNIHSS 10点はDAPTの適応外だが・・・・・・
- しかし、10点でも、脳梗塞の再発Riskは高いので、DAPTは十分検討
- 出血Riskで考える

| Trial名 | Inclusion | 発症からの時間 | 介入 | NNT |
|---------------|---------------|---------------|---------------|---------------|
| CHANCE | ABCD2≧4のTIAあるいはNIHSS≦3の脳梗塞 | 24hr | ASA+CLOを21日 | 28 |
| POINT | ABCD2≧4のTIAあるいはNIHSS≦3の脳梗塞 | 12hr | ASA+CLOを90日 | 67 |
| THALES | ABCD2≧6のTIAあるいはNIHSS≦5の脳梗塞 | 24hr | ASA+CLOを30日 | 91 |
| CHANCE2 | ABCD2≧4のTIAあるいはNIHSS≦3の脳梗塞かつCYP2C19のloss-of-function allele | 24hr | ASA+Ticagrelorを21日 | 63 |
| INSPIRES | ABCD2≧4のTIAあるいはNIHSS≦5の脳梗塞かつアテローム性を疑う | 72hr | ASA+CLOを21日 | 53 |

[@Prabhakaran2026-dz]

## DAPTの出血Risk

- 今回の場合は発症しばらく経過しているが出血Riskは高くなくDAPT導入は十分検討できる
- 裏を返すと、血小板減少とかDIC、原因不明の貧血があったらDAPTは導入しないかも

Todo: DAPTの出血Riskを確認、発症時期により変わるかどうか

## 症例 2

- 82歳女性、HTN, CKD背景
- 3日前発症の左MCA領域の脳塞栓症を発症、来院時のECGでAFを認める
- NIHSSは16点
- 初期治療は？いつ導入する？

## いつ抗凝固を開始するの？

- 心原性脳塞栓患者は、基本的に脳梗塞発症早期が最も再発Riskが高い
  - 古い研究では最初の48時間で4.8%が再発し、抗凝固されないと10日で13%が全身性の塞栓症を発症していた[@Kleindorfer2021-uv; @Hart1983-wi]
- 一方で、脳梗塞範囲が広いため、壊死部位からの出血のRiskも高い
- そのため、早期の抗凝固による予防 vs. 出血のRiskのせめぎあいがあった
- 心原性脳塞栓症患者ではHeparinの24時間以内の早期投与のSystematic reviewで
  - 予後改善なし
  - 出血のみ増加[@Wang2021-ty]
- 結局、**なんとなく弱めにHeparinを開始したりバイアスピリンを早期に導入していた**
  - 超急性期は脳塞栓症であってもバイアスピリンはわずかに予後改善(NNT 140程度)があった[@Chen2000-uo]

## DOAC時代

- DOACはWFに比べて明らかに脳出血を減らし、さらに調整が容易
- 脳塞栓に対して、DOACなら早期導入でよいのではないか？という推定あり

- 4つのRCTがあり、それをまとめると[@Dehbi2025-cu]
  - 早期導入により30日以内の脳梗塞の再発はわずかに減らす(1.68% vs. 2.55%)
  - 早期導入により症候性の脳出血のRiskは変わらない(0.37% vs. 0.36%)
  - ただし、早期導入は4日以内のようなやや曖昧な感じ

## 今回の場合

- NIHSS 16点で、脳梗塞範囲も広く、出血Riskは高い
- しかし、最近のRCTでは、早期導入でも出血Riskは変わらないことが示されている
- 即座のDOACか、24時間程度待って頭部CTを確認した後のDOAC導入が妥当かもしれない

## 症例3

- 症例2の患者を24時間後の頭部CTで左MCAに出血性梗塞を認めた
- 元々脳委縮は大きく、脳ヘルニア兆候やMidline shiftはなし
- 抗凝固はどうする？

## 脳梗塞の出血転化について

- 実はOPTIMAS trialだと軽度の脳出血合併例も入っている[@Werring2024-jg]
  - 出血部位が脳梗塞部位全体の30%未満かつ、圧排がない(Heidelberg criteriaの2未満)
- 全体としてはEarly vs. Late (4日以内 vs. 7日以降)で安全性に差はなし
  - ただし、まだ出血性脳梗塞患者のPrespecifiedのサブ解析は現時点(2026/7/26)では存在しない
- 一方で、ELAN trialのサブ解析では、安全性の差はないが90日での機能予後が悪い可能性がある[@Rohner2024-ww]
- 個人的には出血が広がらないことを同日～翌日まで確認して早期導入がよい(できれば4日以内)
- 当然、神経学的に悪化がなく、脳ヘルニアなどがないことが大前提

## 症例4

- 78歳男性、元々CHADS2 3点で心房細動でEdoxaban 30mgを内服中
- 1日前発症の脳塞栓症あり、NIHSSは3点程度で軽症
- 頸動脈エコーでプラークはなし
- さて、抗凝固はどうする？

## DOAC内服中の脳梗塞

- AF患者へのDOACは脳梗塞Riskを約1/3に低下させる
- 裏を返すと1/3程度の脳梗塞Riskは残る(年率1-2%程度)[@Seiffge2024-yu]
- この時は何故再発したか？をカテゴライズする
  - AF非由来の脳梗塞(アテローム性脳梗塞、Lacunarなど)
  - 内服失敗(Adherence不良、薬剤相互作用、Underdoseなど)
  - 適切な治療にも関わらず再発をした
- 上記2つの場合は各々対応
  - ただし、抗血小板薬+抗凝固は基本行わず、DlpやHTNに対応する

## 適切なDOAC内服中の心原性脳塞栓症再発

- この時にどうすべきかは悩ましい
  - WFに変更
  - 同じDOACを継続
  - DOACの種類を変更
    - 特に、Dabigatran 150mg 2T2Xを考慮(RE-LYで唯一WFに予防効果で勝っている)[@Seiffge2024-yu]
  - ASAを併用　　　　など

## その上で・・・・・・

- AFでDOAC内服中の脳梗塞再発患者へのRCTは存在しない
- 観察研究では、同じ種類のDOACを継続することがその後のRiskが最も低く出血合併症が低かった[@Ip2023-vw]
- 少なくともWFの切り替えやASAの併用は出血Riskが高く、推奨されない[@Romoli2025-ii]
- ただし、いずれにせよ観察研究なので絶対に正しいわけではない
- 個人的には元気な患者の場合は循環器内科に左心耳閉鎖術を相談することも検討する

## 症例5

- 78歳男性、元々HTN, DM, DlpおよびCHADS2 3点で心房細動でEdoxaban 30mgを内服中
- 1日前発症にアテローム性脳梗塞を発症、NIHSSは3点程度で軽症
- どうする？

## アテローム性脳梗塞+AFのRCT

- 日本のRCT

Todo: 確認


## 症例6

- 82歳男性、元々HTN, DM, Dlpで10年前にアテローム性脳梗塞既往
- 動悸で初診外来を受信、新規の心房細動が判明
- どうする？


## 外堀を埋める事実～非心原性脳梗塞の抗血小板薬の治療効果

- WARSS trialではWFは非心原性脳梗塞患者に対してASAと同等の予防効果を認めた[@Mohr2001-ga]
  - 死亡または脳梗塞はWFでやや多いが17.8% vs. 16%で有意差なし
  - 出血はMinorな出血で20.8% vs. 12.9%でWFで有意に多い

## 外堀を埋める事実～心原性脳梗塞の抗凝固の治療効果

- EAFT trialではAF+脳塞栓症の患者に対してPlaceboに比べて再発を1/3まで減らす(OR 0.34, 95% CI 0.20–0.56)[@Klijn2019-ex]

## 外堀を埋める事実～抗凝固の非心原性脳梗塞の予防効果

- 複数のRCTのSystematic reviewだと約15%低下はしていたが統計学的に有意ではなかった[@Klijn2019-ex]

## 外堀を埋める事実～抗血小板と抗凝固の併用の出血Risk

- 探す


## 症例7

- 76歳女性、腎盂腎炎で入院
- 入院日にHR 120の心房細動発症
- 高血圧、糖尿病既往あり

## Secondary (symptomatic) AFの治療は？

- 明らかに原因があるAFで原因が除去された後には不要とされることが多い
- 一方で、AFはなりやすさの素因(Substrate)があるので、"AFになりやすい患者"という考え方もできる
  - この後に永続的AFになるかも
- 実は決まっていない

Todo: ガイドラインのRef

## 今わかっていること

- 二次性AFの患者は1年間追うと1/3が再発し、5年追うと約1/2が再発する
- 二次性AF患者は、その後を追うと死亡率が高く、脳梗塞の発症率も高い
- ただし、二次性のAFは、一次性のAFに比べて脳梗塞Riskは低い
  - CHADS2-VAで1-4点だと1%程度、5-点で2%程度
- 特にSepsisの場合は・・・・・・・

Todo：読んでまとめる

## どうするか？

- 当然、KとかAMI合併とか、甲状腺は確認
- CHADS2は3点と高いため、血栓症のRiskは高いかもしれない
- しかし、Sepsisであり抗凝固の治療効果は観察研究でも証明されていない
  - ある程度の時間(あまり決まっていないが48時間)は抗凝固なしで経過をみて、ずっと続いたら通常のAFとして対応
  - その間に収まったら、本人とShared decision makingをしつつ抗凝固を導入しない風にするかもしれない
- 本人には、AFが再発する可能性が高いことを伝えて動悸があったらすぐに近医受診を勧める

## まとめ



## Thank you for listening

- ご清聴ありがとうございました

## Reference

::: {#refs}
:::